"""Recreate transmissions table

Revision ID: 1a88eb82fcd9
Revises: 649b5a366cf5
Create Date: 2026-07-16 15:54:40.570053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a88eb82fcd9'
down_revision = '649b5a366cf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transmissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dossier_id', sa.Integer(), nullable=False),
    sa.Column('destinataire', sa.String(length=255), nullable=False),
    sa.Column('mode', sa.String(length=50), nullable=False),
    sa.Column('statut', sa.String(length=30), nullable=False),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.Column('cree_par', sa.String(length=100), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers_documentaires.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transmissions')
    # ### end Alembic commands ###
