"""Ajout table transmissions

Revision ID: 649b5a366cf5
Revises: f856500ab997
Create Date: 2026-07-10 17:28:02.793299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '649b5a366cf5'
down_revision = 'f856500ab997'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transmissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dossier_id', sa.Integer(), nullable=False),
    sa.Column('commune', sa.String(length=100), nullable=False),
    sa.Column('date_envoi', sa.DateTime(), nullable=False),
    sa.Column('expediteur', sa.String(length=100), nullable=False),
    sa.Column('statut', sa.String(length=30), nullable=False),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.Column('date_traitement', sa.DateTime(), nullable=True),
    sa.Column('traite_par', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers_documentaires.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dossiers_documentaires', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archive', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('date_cloture', sa.DateTime(), nullable=True))
        batch_op.alter_column('statut',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dossiers_documentaires', schema=None) as batch_op:
        batch_op.alter_column('statut',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('date_cloture')
        batch_op.drop_column('archive')

    op.drop_table('transmissions')
    # ### end Alembic commands ###
