"""Ajout de la table documents

Revision ID: 71f3dcd9a539
Revises: a648cb85a8f4
Create Date: 2026-07-06 11:05:26.159282

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '71f3dcd9a539'
down_revision = 'a648cb85a8f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nom', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('taille', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('date_upload', sa.DateTime(), nullable=False))
        batch_op.alter_column('type_document',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.drop_column('commentaire')
        batch_op.drop_column('statut')
        batch_op.drop_column('date_depot')
        batch_op.drop_column('nom_fichier')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nom_fichier', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('date_depot', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('statut', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('commentaire', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.alter_column('type_document',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('date_upload')
        batch_op.drop_column('taille')
        batch_op.drop_column('nom')

    # ### end Alembic commands ###
