"""Initial schema

Revision ID: a648cb85a8f4
Revises: 
Create Date: 2026-07-06 10:24:58.058015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a648cb85a8f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dossiers_documentaires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_sejour', sa.String(length=20), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('cree_par', sa.String(length=100), nullable=True),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_sejour')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dossier_id', sa.Integer(), nullable=False),
    sa.Column('type_document', sa.String(length=100), nullable=False),
    sa.Column('nom_fichier', sa.String(length=255), nullable=False),
    sa.Column('chemin_fichier', sa.String(length=500), nullable=False),
    sa.Column('date_depot', sa.DateTime(), nullable=False),
    sa.Column('statut', sa.String(length=30), nullable=False),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers_documentaires.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents')
    op.drop_table('dossiers_documentaires')
    # ### end Alembic commands ###
