"""Ajout table audit_logs

Revision ID: f856500ab997
Revises: 4b7c5923002a
Create Date: 2026-07-08 08:56:47.305024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f856500ab997'
down_revision = '4b7c5923002a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilisateur', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('objet', sa.String(length=255), nullable=True),
    sa.Column('adresse_ip', sa.String(length=45), nullable=True),
    sa.Column('date_action', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
